#!/bin/bash

export BAR=false
../include -DNAME=Alice input.txt.include >output_a.txt

export BAR=something
../include -DNAME=Bob input.txt.include >output_b.txt

../include -DNAME=Charlie -DFOO="Hello, world!" -PEXTRASTUFF input.txt.include >output_c.txt

../include -DFOO=true recursive.txt >output_recursive.txt

../include -DFOO=true hashy.txt >output_hashy.txt

diff output_recursive_correct.txt output_recursive.txt
if [ $? -ne 0 ]
then
  echo "nested if block test failed!"
fi

diff output_hashy_correct.txt output_hashy.txt
if [ $? -ne 0 ]
then
  echo "the hash-hash macro failed!"
fi

diff output_a_correct.txt output_a.txt
if [ $? -ne 0 ]
then
  echo "output_a test failed!"
fi

diff output_b_correct.txt output_b.txt
if [ $? -ne 0 ]
then
  echo "output_b test failed!"
fi

diff output_c_correct.txt output_c.txt
if [ $? -ne 0 ]
then
  echo "output_c test failed!"
fi

../include shoulderror.txt >/dev/null 2> /dev/null
if [ $? -eq 0 ]
then
  echo "Processing shoulderror.txt failed to fail!"
fi

